/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://bxyovq5nb5fldnptclpme7p7ze.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-uqgjlt66fnclhovei6up4mlw7q",
    "aws_cloud_logic_custom": [
        {
            "name": "restapi",
            "endpoint": "https://lk5npz3rrd.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:ddd2d042-47b9-4265-bd01-fcd0434ddafb",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_jpmhIHo41",
    "aws_user_pools_web_client_id": "2p4d81j1tjv483qb64nqc5nk5a",
    "oauth": {},
    "aws_user_files_s3_bucket": "photobiebdfef672c8ef4982a8927c135f907a5f213745-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
