/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://fyigvbbfkzal3amxasgvtoq7yu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5tc53jmabfes3gmimw6i5g46uu",
    "aws_cloud_logic_custom": [
        {
            "name": "paymentapi",
            "endpoint": "https://ntish65xfb.execute-api.us-east-1.amazonaws.com/dev",
            "region": "us-east-1"
        }
    ],
    "aws_cognito_identity_pool_id": "us-east-1:36a5b6e9-6391-4d7e-a9ce-12a212cc6e53",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_dwsS325sm",
    "aws_user_pools_web_client_id": "4r5jfjp9koldi9udepdj5m9j14",
    "oauth": {},
    "aws_user_files_s3_bucket": "photobie1fae69e761734cfd81b6f1767c7a5c9b72158-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
